// Mocks generated by Mockito 5.0.14 from annotations
// in sandbox/test/todo/todo_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:sandbox/todo/model.dart' as _i3;
import 'package:sandbox/todo/repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Todo> get todos =>
      (super.noSuchMethod(Invocation.getter(#todos), returnValue: <_i3.Todo>[])
          as List<_i3.Todo>);
  @override
  void addTodo(_i3.Todo? todo) =>
      super.noSuchMethod(Invocation.method(#addTodo, [todo]),
          returnValueForMissingStub: null);
  @override
  void updateTodo(_i3.Todo? toBeUpdated, _i3.Todo? updatedTodo) => super
      .noSuchMethod(Invocation.method(#updateTodo, [toBeUpdated, updatedTodo]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
